name: casino_test
description: Casino test application

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.13.4 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc_concurrency: ^0.2.1
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.7.0
  fluttertoast: ^8.2.1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_fonts: ^4.0.4
  http: ^0.13.4
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.4.0
  mockito: ^5.4.0
  provider: ^6.0.5
  splashscreen: ^1.3.5
  timeago: ^3.4.0

dev_dependencies:
  build_runner: ^2.0.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true
